In [275]:
import numpy as np
from sklearn.datasets import load_iris

<h3>[Problem 1] Enumeration of classes used so far</h3>

<h4>from Scikit-learn</h4>

- StandardScaler()
- DecisionTreeClassifier()
- RandomForestRegressor()

<h4>from pandas</h4>

- DataFrame()
- Series()

<h4>from mathplotlib</h4>

- Axes()
- Figure()

<h3>[Problem 2] Enumeration of methods and instance variables used so far</h3>

<h4>numpy.array()</h4>

- shape: Tuple of array dimensions
- size: Number of elements in the array
- ndim: Number of array dimensions
- T: Transpose array
- dtype: Data-type of the array’s elements 
- reshape(): rearrange the array dimension
- resize(): Change shape and size of array in-place
- astype(): Copy of the array, cast to a specified type
- copy(): return a copy of the array
- sort(): sort the array

<h4>pandas.DataFrame()</h4>

- index: The index (row labels) of the DataFrame
- columns: The columns label of the DataFrame
- dtype: Data-type of the DataFrame’s elements
- size: Return an int representing the number of elements in this object
- shape: Return a tuple representing the dimensionality of the DataFrame
- head(n): Return the first n rows 
- info(): Print a concise summary of a DataFrame (shape, dtype,...)
- describe(): Generate descriptive statistics
- isnull(): Detect missing values
- query(): Query the columns of a DataFrame with a boolean expression.

<h3>[Problem 3] Creating a standardized class by scratch</h3>

In [277]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = np.array((X-self.mean_) / (self.var_**(1/2)))

        return X_scaled

In [278]:
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


<h3>[Problem 4] Creating a class that performs 4 arithmetic operations</h3>

In [279]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        if (type(value) is not (int or float)):
            raise TypeError("Input value must be float or int")
        else:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        

    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    
    def sub(self, value2):
        self.value -= value2

    def mul(self, value2):
        self.value *= value2

    def div(self, value2):
        if (value2 == 0):
            raise Exception("Division by zero")
        else:
            self.value /= value2
        
try:
    example = ExampleClass(10)
    example.add(3)
    print("value : {}".format(example.value))
    example.sub(-3)
    print("value : {}".format(example.value))
    example.mul(5.5)
    print("value : {}".format(example.value))
    example.div(0)
    print("value : {}".format(example.value))
except Exception as err:
    print(err)

try:
    example2 = ExampleClass("abc")
except Exception as err:
    print(err)

初期値10が設定されました
value : 13
value : 16
value : 88.0
Division by zero
Input value must be float or int
