In [36]:
import numpy as np

<h3>[Problem 1] Matrix product is calculated manually<h3>

A is a matrix m x n; B is a matrix n x p. So the result matrix C has a shape m x p. <br>
The calculation process for each result cell: <br>

$c_{ij} = \sum \limits _{k=1} ^{n} a_{ik}*b_{kj}$

for i = 1 to m (representing the row); j = 1 to p (representing the column) <br>
Repeat the step for m x p cell <br>
----------------<br>
A is a 3 x 3 matrix; b is a 3 x 3 matrix. So the result matrix C has a shape 3 x 3 <br>
Calculating for each cell using the formula: <br>

$c_{ij} = \sum \limits _{k=1} ^{3} a_{ik}*b_{kj}$

for i = 1 to 3; j = 1 to 3 <br>
Repeat the step for 9 cell <br>

We get the result matrix:
$\begin{bmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48 \end{bmatrix}$



<h3>[Problem 2] Calculation by NumPy function<h3>

In [37]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [38]:
print("The product matrix of the multiplication A * B: \n{}".format(np.matmul(a_ndarray, b_ndarray)))

The product matrix of the multiplication A * B: 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<h3>[Problem 3] Implementation of calculation of a certain element<h3>

In [39]:
i = 1
j = 2

%timeit c_ij = sum(a_ndarray[i, k] * b_ndarray[k, j] for k in range(0, a_ndarray.shape[1]))
%timeit c_ij = sum(a_ndarray[i,:] * b_ndarray[:, j])

2.23 µs ± 67.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.76 µs ± 35.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
print("Result at cell ({}, {}): {}".format(i, j, c_ij))

Result at cell (1, 2): 38


<h3>[Problem 4] Creating a function that performs matrix multiplication<br>
and [Problem 5] Judge the input whose calculation is not defined<h3>

In [41]:
def matrix_multiplication(a_matrix, b_matrix):
    """
    A function that compute the matrix multiplication matrix a * matrix b.
    Parameter:
    --------------
    a_matrix: np.array
        matrix a
    b_matrix: np.array
        matrix b
    Return:
    --------------
    A result matrix: np.array
    or print to the screen if the input is invalid
    """
    
    if (a_matrix.shape[1] != b_matrix.shape[0]):
        print("Invalid input")
        return
    
    c_matrix = np.array([])
    for i in range(0, a_matrix.shape[0]):
        for j in range(0, b_matrix.shape[1]):
                c_matrix = np.append(c_matrix, sum(a_matrix[i, k] * b_matrix[k, j] 
                                                        for k in range(0, a_matrix.shape[1])))
    
    return c_matrix.reshape(a_matrix.shape[0], b_matrix.shape[1])

In [50]:
def matrix_multiplication_2(a_matrix, b_matrix):
    """
    A function that compute the matrix multiplication matrix a * matrix b.
    Parameter:
    --------------
    a_matrix: np.array
        matrix a
    b_matrix: np.array
        matrix b
    Return:
    --------------
    A result matrix: np.array
    or print to the screen if the input is invalid
    """
    
    if (a_matrix.shape[1] != b_matrix.shape[0]):
        print("Invalid input")
        return
    
    c_matrix = np.array([])
    for i in range(0, a_matrix.shape[0]):
        for j in range(0, b_matrix.shape[1]):
                c_matrix = np.append(c_matrix, sum(a_matrix[i,:] * b_matrix[:, j]))
    
    return c_matrix.reshape(a_matrix.shape[0], b_matrix.shape[1])

In [43]:
print("The product matrix of the multiplication A * B: \n{}".format(matrix_multiplication(a_ndarray, b_ndarray)))

The product matrix of the multiplication A * B: 
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [51]:
%timeit matrix_multiplication(a_ndarray, b_ndarray)
%timeit matrix_multiplication_2(a_ndarray, b_ndarray)

72.7 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
87.3 µs ± 1.66 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [45]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [46]:
print("The product matrix of the multiplication D * E: \n{}".format(matrix_multiplication(d_ndarray, e_ndarray)))

Invalid input
The product matrix of the multiplication D * E: 
None


In [47]:
%timeit np.matmul(a_ndarray, b_ndarray)
%timeit np.dot(a_ndarray, b_ndarray)
%timeit a_ndarray @ b_ndarray
%timeit matrix_multiplication(a_ndarray, b_ndarray)

970 ns ± 38.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.03 µs ± 15.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
944 ns ± 17.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
72.3 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


<h3>[Problem 6] Transposition<h3>

In [48]:
print("The product matrix of the multiplication D.T * E: \n{}".format(matrix_multiplication(d_ndarray.T, e_ndarray)))

The product matrix of the multiplication D.T * E: 
[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]


In [49]:
print("The product matrix of the multiplication D * E.T: \n{}".format(matrix_multiplication(d_ndarray, e_ndarray.T)))

The product matrix of the multiplication D * E.T: 
[[ 46.  -4.]
 [-34.  73.]]


In [52]:
%%timeit
a = []
for i in range(0, 10000):
    a.append(i)

470 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [53]:
%%timeit
b = [i for i in range(0, 10000)]

257 µs ± 5.54 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
